
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import "../globals.css";
//import { ClerkProvider,  SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en" className=" bg-white">
      <body >   
      <Navbar/>    
        {children}  
        <Footer/>    
        </body>
    </html>
   
  );
}
