
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import { Providers } from "./redux/provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en" className=" bg-white">
      <body >    
        <Providers>
        {children}      
        </Providers>   
        </body>
    </html>
    </ClerkProvider>
  );
}
